name    'ft-kafka_bridge'
version '0.0.0'
source 'UNKNOWN'
author 'ft'
license 'Apache License, Version 2.0'
summary 'UNKNOWN'
description 'UNKNOWN'
project_page 'UNKNOWN'

## Add dependencies, if any:
dependency 'ft/common_pp_up', '>=0.0.1'
dependency 'ft/satellitesubscribe', '0.0.x'
