apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pub-auth
  namespace: default
  type: Opaque
spec:
  encryptedData:
{{ if .Values.pubAauth }}{{ toYaml .Values.pubAauth | indent 4 }}{{ end }}
