# Default values for coco-kafka-bridge.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
service:
  hasHealthcheck: "true"
image:
  repository: coco/coco-kafka-bridge
bridges: # The bridges should be defined in the app config file
limits:
  memory: 256Mi
