# Default values that will be applied to team clusters.
# In team clusters, in delivery we have bridges only to the pub cluster of the team env

bridges:
## BEGIN pub-cj bridges
##CMS
- name: cms-kafka-bridge-pub-dev-cj-eu
  sourceKafkaProxyUrl: "https://upp-dev-cj-publish-eu.ft.com"
  groupIdPrefix: kafka-bridge-pub-dev-cj-eu
  topic: NativeCmsPublicationEvents
  producer: "http://cms-notifier:8080"
  authSecretName: pub-auth
  authSecretKey: pub-dev-cj-auth
  type: "plainHTTP"
  replicas: 2
#CMS metadata
- name: cms-metadata-kafka-bridge-pub-dev-cj-eu
  sourceKafkaProxyUrl: "https://upp-dev-cj-publish-eu.ft.com"
  groupIdPrefix: metadata-kafka-bridge-pub-dev-cj-eu
  topic: NativeCmsMetadataPublicationEvents
  authSecretName: pub-auth
  authSecretKey: pub-dev-cj-auth
  type: "proxy"
  replicas: 2
## END pub-cj bridges
