# Default values that will be applied to team clusters.
# In team clusters, in pub we have bridges to both Prod and Staging to all regions.

bridges:
## Begin prod bridges
#CMS
- name: cms-kafka-bridge-pub-prod-eu
  kafkaProxyUrl: "https://upp-prod-publish-eu.ft.com"
  groupIdPrefix: kafka-bridge-pub-prod-eu
  topic: NativeCmsPublicationEvents
  authSecretName: pub-auth
  authSecretKey: pub-prod-auth
  replicas: 2
- name: cms-kafka-bridge-pub-prod-us
  kafkaProxyUrl: "https://upp-prod-publish-us.ft.com"
  groupIdPrefix: kafka-bridge-pub-prod-us
  topic: NativeCmsPublicationEvents
  authSecretName: pub-auth
  authSecretKey: pub-prod-auth
  replicas: 2
#CMS metadata
- name: cms-metadata-kafka-bridge-pub-prod-eu
  kafkaProxyUrl: "https://upp-prod-publish-eu.ft.com"
  groupIdPrefix: metadata-kafka-bridge-pub-prod-eu
  topic: NativeCmsMetadataPublicationEvents
  authSecretName: pub-auth
  authSecretKey: pub-prod-auth
  replicas: 2
- name: cms-metadata-kafka-bridge-pub-prod-us
  kafkaProxyUrl: "https://upp-prod-publish-us.ft.com"
  groupIdPrefix: metadata-kafka-bridge-pub-prod-us
  topic: NativeCmsMetadataPublicationEvents
  authSecretName: pub-auth
  authSecretKey: pub-prod-auth
  replicas: 2

# Concepts 
- name: concepts-kafka-bridge-pub-pub-prod-eu
  kafkaProxyUrl: "https://upp-prod-publish-eu.ft.com"
  groupIdPrefix: concepts-kafka-bridge-pub-prod-eu
  topic: Concept
  authSecretName: pub-auth
  authSecretKey: pub-prod-auth
  replicas: 1
- name: concepts-kafka-bridge-pub-pub-prod-us
  kafkaProxyUrl: "https://upp-prod-publish-us.ft.com"
  groupIdPrefix: concepts-kafka-bridge-pub-prod-us
  topic: Concept
  authSecretName: pub-auth
  authSecretKey: pub-prod-auth
  replicas: 1
## END prod bridges

## Start staging bridges
# todo point the staging bridges to the k8s staging env, when we provision this env.
##CMS
- name: cms-kafka-bridge-pub-staging-eu
  kafkaProxyUrl: "https://pub-pre-prod-uk-up.ft.com"
  groupIdPrefix: kafka-bridge-pub-staging-eu
  topic: NativeCmsPublicationEvents
  authSecretName: pub-auth
  authSecretKey: pub-staging-auth
  replicas: 2
- name: cms-kafka-bridge-pub-staging-us
  kafkaProxyUrl: "https://pub-pre-prod-us-up.ft.com"
  groupIdPrefix: kafka-bridge-pub-staging-us
  topic: NativeCmsPublicationEvents
  authSecretName: pub-auth
  authSecretKey: pub-staging-auth
  replicas: 2
#CMS metadata
- name: cms-metadata-kafka-bridge-pub-staging-eu
  kafkaProxyUrl: "https://pub-pre-prod-uk-up.ft.com"
  groupIdPrefix: metadata-kafka-bridge-pub-staging-eu
  topic: NativeCmsMetadataPublicationEvents
  authSecretName: pub-auth
  authSecretKey: pub-staging-auth
  replicas: 2
- name: cms-metadata-kafka-bridge-pub-staging-us
  kafkaProxyUrl: "https://pub-pre-prod-us-up.ft.com"
  groupIdPrefix: metadata-kafka-bridge-pub-staging-us
  topic: NativeCmsMetadataPublicationEvents
  authSecretName: pub-auth
  authSecretKey: pub-staging-auth
  replicas: 2

# Concepts
- name: concepts-kafka-bridge-pub-pub-staging-eu
  kafkaProxyUrl: "https://pub-pre-prod-uk-up.ft.com"
  groupIdPrefix: concepts-kafka-bridge-pub-staging-eu
  topic: Concept
  authSecretName: pub-auth
  authSecretKey: pub-staging-auth
  replicas: 1
- name: concepts-kafka-bridge-pub-pub-staging-us
  kafkaProxyUrl: "https://pub-pre-prod-us-up.ft.com"
  groupIdPrefix: concepts-kafka-bridge-pub-staging-us
  topic: Concept
  authSecretName: pub-auth
  authSecretKey: pub-staging-auth
  replicas: 1
## END staging bridges
